kind: Deployment
apiVersion: apps/v1
metadata:
   name: webapp-deployment
spec:
   replicas: 3
   selector:     
      matchLabels:
         app: webapp-deployment
   template:
      metadata:
         labels:
            app: webapp-deployment
      spec:
         containers:
            - name: webapp-deployment
              image: testingkyaw/pet-clinic-app-cicd-pipeline:v1.98
              imagePullPolicy: Always
              ports:
               - containerPort: 8080
